# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/geoflois31/Documents/Partie3/TP_Micro1.cache/wt [current_project]
set_property parent.project_path C:/Users/geoflois31/Documents/Partie3/TP_Micro1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/geoflois31/Documents/IP [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/geoflois31/Documents/Partie3/TP_Micro1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/hdl/ublaze_wrapper.v
add_files C:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ublaze.bd
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_0_0/ublaze_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_0_0/ublaze_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_0_0/ublaze_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_1/ublaze_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_1/ublaze_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_1/ublaze_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_2_0/ublaze_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_2_0/ublaze_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_2_0/ublaze_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_bram_if_cntlr_0/ublaze_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_bram_if_cntlr_0/ublaze_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_lmb_bram_0/ublaze_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_xbar_0/ublaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_axi_intc_0/ublaze_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_axi_intc_0/ublaze_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_axi_intc_0/ublaze_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_0_100M_0/ublaze_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_0_100M_0/ublaze_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_0_100M_0/ublaze_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ublaze_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_1/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/constrs_1/imports/Docts_Basys3/basys3_master.xdc
set_property used_in_implementation false [get_files C:/Users/geoflois31/Documents/Partie3/TP_Micro1.srcs/constrs_1/imports/Docts_Basys3/basys3_master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ublaze_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ublaze_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ublaze_wrapper_utilization_synth.rpt -pb ublaze_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
