webtalk_init -webtalk_dir C:\\Users\\geoflois31\\Microelectronique\\TP_Micro1\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-03-26 14:18:29" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210647190_0_0_243" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9gtflisfqgekliqmng7kfd6ust" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.002 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1774530861637" -context "sdk\\\\bsp/1774530861637"
webtalk_add_data -client sdk -key hwid -value "1771233590000" -context "sdk\\\\bsp/1774530861637"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1774530861637"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1774530861637"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1774530861637"
webtalk_add_data -client sdk -key uid -value "1774530862967" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key hwid -value "1771233590000" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key bspid -value "1774530861637" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key projSize -value "87.5703125" -context "sdk\\\\application/1774530862967"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1774531109839"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1774531109839"
webtalk_transmit -clientid 3016385272 -regid "210647190_0_0_243" -xml C:\\Users\\geoflois31\\Microelectronique\\TP_Micro1\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\geoflois31\\Microelectronique\\TP_Micro1\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\geoflois31\\Microelectronique\\TP_Micro1\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
